name: Matrix strategy workflow
run-name: Matrix strategy workflow run 

on:
  workflow_dispatch:

jobs:
  install-java:
    name: install java
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17]
    steps: 
      - name: setup java
        uses: actions/setup-jave@v4
        with:
          java-version: ${{ matrix.java-version }}
