name: Matrix strategy workflow
run-name: Matrix strategy workflow run 

on:
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  install-java:
    name: install java
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        java-version: [11, 17]
    steps: 
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
      
      - name: Build app
        run: echo "Building with Java ${{ matrix.java-version }}"
      
      - name: print git inbuilt env vars
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_SHA"
        shell: bash

